{% set name = "pytest-pylint" %}
{% set version = "0.13.0" %}
{% set sha256 = "50500fa8ecd7f7ca8e1d08e4c2c8748ae376a95745d3574861a86d642d9ed9b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - six
    - pylint >=1.4.5
    - pytest >=2.7

test:
  imports:
    - pytest_pylint

about:
  home: https://github.com/carsongee/pytest-pylint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'pytest plugin for running pylint against your codebase'
  description: |
    Run pylint with pytest and have configurable rule types (i.e. Convention, 
    Warn, and Error) fail the build. You can also specify a pylintrc file.
  doc_url: https://github.com/carsongee/pytest-pylint
  dev_url: https://github.com/carsongee/pytest-pylint

extra:
  recipe-maintainers:
    - holgern
