{% set name = "pytest-pylint" %}
{% set version = "0.16.0" %}
{% set sha256 = "74c9e8655670fc82359a441e4d03aaa88705ea1d838f258d91e74d42bd77ba65" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - six
    - pylint >=1.4.5
    - pytest >=2.7
    - pytest-runner

test:
  imports:
    - pytest_pylint

about:
  home: https://github.com/carsongee/pytest-pylint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin for running pylint against your codebase
  description: |
    Run pylint with pytest and have configurable rule types (i.e. Convention, 
    Warn, and Error) fail the build. You can also specify a pylintrc file.
  doc_url: https://github.com/carsongee/pytest-pylint
  dev_url: https://github.com/carsongee/pytest-pylint

extra:
  recipe-maintainers:
    - holgern
