{% set name = "pytest-pylint" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a38be02c014eb6d98791eb978e79ed292f1904d3a518289c6d7ac4fb4122e98

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.8
    - pip
    - pytest-runner
  run:
    - python >=3.8
    - setuptools
    - pylint >2,<4
    - pytest >=4.6

test:
  imports:
    - pytest_pylint

about:
  home: https://github.com/carsongee/pytest-pylint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin for running pylint against your codebase
  description: |
    Run pylint with pytest and have configurable rule types (i.e. Convention, 
    Warn, and Error) fail the build. You can also specify a pylintrc file.
  doc_url: https://github.com/carsongee/pytest-pylint
  dev_url: https://github.com/carsongee/pytest-pylint

extra:
  recipe-maintainers:
    - holgern
    - n-elie
