{% set name = "pytest-pylint" %}
{% set version = "0.19.0" %}
{% set sha256 = "d88e83c1023c641548a9ec3567707ceee7616632a986af133426d4a74d066932" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - six
    - pylint >=2.3.0
    - pytest >=5.4
    - pytest-runner
    - toml >=0.7.1

test:
  imports:
    - pytest_pylint

about:
  home: https://github.com/carsongee/pytest-pylint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin for running pylint against your codebase
  description: |
    Run pylint with pytest and have configurable rule types (i.e. Convention, 
    Warn, and Error) fail the build. You can also specify a pylintrc file.
  doc_url: https://github.com/carsongee/pytest-pylint
  dev_url: https://github.com/carsongee/pytest-pylint

extra:
  recipe-maintainers:
    - holgern
