travis:
  secure:
    BINSTAR_TOKEN: Q3uo/0tpUoOXLCP08rghQqlM+J8mhsDHMgCxFPANU/bms2JAYmNYCG0ddRN9AwvwRpOXT8ySUePoOZb88hnuPv7Ot8igsUu1F8cvhaCAzsbQprM1PJtWCT7xZLT//Ae0+TajHabsBznlqUM6a6riFuohU0C1Squ8vTxin3yxYBPhUKJdDi8Ms33VZRgpgulBMu7OZKSgBPOC7cboRErd72o6dO7qAkO6hP7zPnD+yLUeb4Qh0pdpvVL779D3UMQpU7HoWRBcjsNwxYpJcMJ6lSiAW/HjZVR1idhLE0YPox3I6h3Gbtl+/W1QK8SD4HkX/JJpYXfnEWP6TbBMmM8AFjx2KxK5u5nvUO6BpEXMR/N+uV5L5bw/o7R3alfRryaFzY0aidFzAHzGYvB3BDaUwMWU26jqkIDiNN91LlEO4ur3mOBe13Og/9rztjKc89w2ss8baMjdO9/D32Zm1PbaGHCuW2Q6W3gzyvnx5mQn6QCHCSx+vv0xIdwoGWvp5vZF1Wuv1q6THBn7nELlMcrVNShKRRr5tIraroDCxvuOaqxzi2BV1mOgQlfTEe2ky11bO8a6W12cGmsFoWR2GggNjp/gOS2revISuDJm0Q0mg6E5mGn8Ohmoiu/f5a0AHFCcCwij2JnpsIhAPH5JOmoAsGfqcoT2VN975Wo99mshhDE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
